version: '3.9'

services:
  mysql:
    build:
      context: ./services/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306" # Map MySQL port to host
    volumes:
      - mysql_volume:/var/lib/mysql # Persistent storage for MySQL data
    env_file:
      - ./services/mysql/.env # Load environment variables from .env file
    networks:
      - phpmyadmin-mysql

  phpmyadmin:
    build:
      context: ./services/phpmyadmin
      dockerfile: Dockerfile
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - ./services/phpmyadmin/.env # Load environment variables from .env file
    networks:
      - phpmyadmin-mysql

networks:
  phpmyadmin-mysql:

volumes:
  mysql_volume: