version: '3.9'

networks:
  phpmyadmin-mysql:

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    env_file: .env
    networks:
      - phpmyadmin-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: "265M"
      PHP_UPLOAD_MAX_FILESIZE: "64M"
      PHP_MAX_INPUT_VARS: "1000"
      PHP_MEMORY_LIMIT: "256M"
      PHP_SESSION_TIMEOUT: "1440"
      PHP_MAX_EXECUTION_TIME: "600"
    networks:
      - phpmyadmin-mysql

volumes:
  mysql_volume: